language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install --save fs-extra
script:
  - npm run build
env:
  - NODE_ENV=production
notifications:
  slack: rheinklang:BzAHcIwDekK6y8FmuOCPdW4t
