language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
install:
  - npm install --no-optional
script:
  - npm run build
env:
  - NODE_ENV=development
notifications:
  slack: rheinklang:BzAHcIwDekK6y8FmuOCPdW4t
